# Generated by Django 2.0.4 on 2018-04-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
